language: node_js
node_js:
  - '6'
branches:
  only:
    - ui
before_install: if [[ `npm -v` != 3* ]]; then npm i -g npm@3; fi
before_script:
  - npm install -g angular-cli@1.0.0-beta.30
script: ./travis-build.sh
env:
  global:
  - GIT_NAME="James Kleeh"
  - GIT_EMAIL="james.kleeh@gmail.com"
  - secure: Fl8+X5WrCR+kxB+fNCYoZIH40PV1kZd4MuzpJXaSZP7r6u0wA7An6ww2WONRjLkJ3A0La2+kSkjdnt5tduNKa+KGi5yBUr4bVcKhBBvXBr3YRZAMpaC2x4CLTxRl9YrcBnRHBre+zTym9jV1XiF541pBo57NOK+QEmitwR5Ow5p2PJ/5+Mznp5IeY6TftPpzK5bO6cJP149zDTVTqXL6YVKvFIJzyCJ48Sr1i4mw/mwgotBuErgdAqUttGfWQgyeji9I13YEtymTFk1bjr6QyR3wPMFDwrIG49hxzyj3Dl+P47S1wSANXrfAKKJc5K6rpy+u1LZsD9vsTl6opB9z5Dg0e0Z/ES8hDKqKMuyD0aXWoc6mqKH+njsjrDBjEKtaRMNya4u+uUjL3U+vfcvtPBXPWLlm5bOrW4rxG5zKwdAJdIPHORgW6wWyXwypWdAJ8CLttDGPO/nUZnhCmIsW9d3x8QCErLiHyoKh2lI+wwF0QRsSiPv1Wwy9EoYGEFaM/4PeATlomBbc6NdfLRMW6qIvin2LW2PCKg25dFdrbO5Qju4MLVPP8o2Ec3fOFKAlsaW4vJbOY+iBsQ0ESEiPklmZiAQ4ywaTGNmbmhrZ//HF/ew1MyKKZGwcW+XWHScfX20cNnOZWcUGdvQGbYCbil07pFy4ciNpeaKVq2fr5dI=
